//Introdução JavaScript

//Tipos de Dados (Escopo, Tipagem)

//Tipo String
var nome = "João"; //Declaração da Variável Nome
nome = "Pedro"; // Redefinindo o Valor
var nome = "Maria"; //Redeclarando

//Tipo Números
let idade = 25; //Declarando a Idade
idade = 30; // Redefini o valor
// let idade = 40; // não pode Redeclarar LET

//tipo number
const PI = 3.14;
// PI = 3.33; //erro valor -
// const PI = 4.56; // não pode redeclarar


//tipo boolean
var aprovado = true;
aprovado = false; //posso alterar tranquilamente

// Tipo umdefined
var media;

// Tipo null - vazio
var info = null;

//Printar as informações

console.log("Nome " + nome);
console.log("idade " + idade);
console.log("PI " + PI);
console.log("Aprovado " + aprovado);
console.log("média " + media);
console.log("informação " + info);